TN-3037 Fetching Tonic version number instead of using latest
TonicAI/tim pull request #38
Opened 2022-11-11 21:09 UTC by daniel-tonic

2022-11-11 21:41 UTC, anr-tonic requested changes

2022-11-11 21:41 UTC, anr-tonic commented on cli/pkg/chart/chart.go
> +
We'll be better off doing this in `CollectBaseTonicValues` instead of here because we can just set version tag directly on the configuration object:

```go
func CollectBaseTonicValues(...) ... {
    if values == nil { .. }
    values.Version = getLatestTonicVersion()
    collector := ...
}
```

And instead of `getLatestTonicVersion` returning `err` it can always return a string because even if it failed to get the actual latest version it can just return `latest`

2022-11-11 22:18 UTC, daniel-tonic commented on cli/pkg/chart/chart.go
> +
request granted

2022-11-14 15:10 UTC, anr-tonic approved these changes

2022-11-14 15:23 UTC, merged