TN-3076 - Automatically output/load helm values file to/from working directory
TonicAI/tim pull request #40
Opened 2022-11-14 21:45 UTC by daniel-tonic

2022-11-15 20:28 UTC, anr-tonic requested changes

2022-11-15 20:28 UTC, anr-tonic commented on cli/pkg/types/helmfile.go
> +		return nil, errors.New("Could not get chart values file name: " + err.Error());
```suggestion
		return fmt.Errorf("Could not get chart values file name: %w", err)
```

For all of the `errors.New("..." + err.Error())` instances.

2022-11-15 20:28 UTC, anr-tonic commented on cli/pkg/chart/chart.go
> +	err := tt.WriteTonicChartValuesToFile(installValues, chartValues, io.MultiWriter())
Why pass a new multiwriter each time instead of `w`?

2022-11-15 20:57 UTC, daniel-tonic commented on cli/pkg/chart/chart.go
> +	err := tt.WriteTonicChartValuesToFile(installValues, chartValues, io.MultiWriter())
Because intellisense corrected it at some point, I didn't notice, then the copy/paste monster got me, and it worked so I didn't double check it. heh

2022-11-15 20:58 UTC, daniel-tonic commented on cli/pkg/types/helmfile.go
> +		return nil, errors.New("Could not get chart values file name: " + err.Error());
no one ever lets me concatenate anymore!

2022-11-16 16:36 UTC, anr-tonic commented on cli/pkg/types/helmfile.go
> +		return nil, errors.New("Could not get chart values file name: " + err.Error());
If `fmt.Errorf("... %w", err)` wasn't the "idiomatic" way of wrapping errors I don't think I'd mind since Go seems to have similar performance around `string + string` and `fmt.Sprintf("...", some,  more, string)`

2022-11-16 16:36 UTC, anr-tonic commented on cli/pkg/chart/chart.go
> +	err := tt.WriteTonicChartValuesToFile(installValues, chartValues, io.MultiWriter())
👍 wanted to be sure there wasn't something I was missing lol

2022-11-17 18:37 UTC, anr-tonic approved these changes

2022-11-17 18:42 UTC, merged